### ISSUE TITLE
Bower - angular-bootstrap now is 0.12

### ISSUE THREAD

**Issue by piernik** [m-e-conroy/angular-dialog-service#104]
Can You change angular-bootstrap depency to '^0.11' - it now is at 0.12 and soon will be 0.13

Edit:
and You've got `angular-translate as depency - shouldn't it be optional?

**Comment by oharlem** [comment]
Same here. ui-bootsrtap is 0.12.1 now, but updated makes it downgrade to 0.11.2

P.S.
Thank you for the dialog service!!

**Comment by m-e-conroy** [comment]
If you bower installed angular-bootstrap previously and then tried to install this package it should give you the option to use the already installed version so long as its 0.11 and above.  If it doesn't let me know, I did push it up to 0.12, in order to maintain compatibility with both versions 0.12 and 0.13.  Version 5.2.8 should work better with Angular-Bootstrap 0.13 as there is a bug with 0.13 when using Angular 1.4.
