### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by dougmoscrop** [m-e-conroy/angular-dialog-service#114]
Any idea when next release / merge some PRs is going to happen? Do you need help with maintaining this?

**Comment by ayush** [comment]
+1 It'll be nice to see an update. Angular bootstrap also released 0.13.0 https://github.com/angular-ui/bootstrap/commit/4c6e0b3b2eeb443b9370ca12ae2ef90d445036c4

**Comment by niemyjski** [comment]
+!, @dougmoscrop  I'd say yes.

**Comment by niemyjski** [comment]
@m-e-conroy, If you want to add @dougmoscrop and myself to the repo.. We'll try and help out where we can.. I can't commit to much right now other than testing/looking/accepting at pull requests and ensuring that bower is up to date.

**Comment by m-e-conroy** [comment]
I just release 5.2.8, adding the ability to use the `animation` and `backdropClass` options of Angular-Bootstrap modal.  Hopefully this will help with thwarting the problem caused by the combo of Angular-Bootstrap 0.13.0 and Angular 1.4's ngAnimate.

@dougmoscrop @niemyjski I've added you both as collaborators.

**Comment by niemyjski** [comment]
Awesome! thank you!
