### ISSUE TITLE
version 5.2.9 should not have been a patch version update and should have been 5.3.0 due to minor version increment in angular-bootstrap version (0.13 to 0.14) 

### ISSUE THREAD

**Issue by plite** [m-e-conroy/angular-dialog-service#156]
5.2.9 introduced a newer version of angular bootstrap dependency (.014)for which is not backwords compatible with 0.13. 

If a project is also dependent on angular bootstrap and uses 0.13 and angular dialog service 5.2.9 this will break functionality

a good rule of thumb is even if you are changing a minor version of a dependency then you should increment your own minor version.

**Comment by dougmoscrop** [comment]
Agreed - this was an oversight, what would you propose we do now?

**Comment by niemyjski** [comment]
Yeah this was my bad. It was under the assumption that everyone was already on it and I should have bumped it.

**Comment by spongessuck** [comment]
I just ran into this issue- used `bower update` and it broke my code which was pointing to ui-bootstrap 13.4 and this repo ~5.2.6 (it installed 5.2.11).

You could rerelease the versions since 5.2.9 as 5.3.x and deprecate the 5.2 versions in npm and bower- that would at least give people installing them a warning that they should use 5.3.x instead and restore semantic versioning.
