### ISSUE TITLE
Anything special needed to capture modal/dialog resize events?

### ISSUE THREAD

**Issue by aaronjessen** [m-e-conroy/angular-dialog-service#95]
I've been successful in setting up your service and opening/closing modals (thanks for creating such an awesome solution!). Rather than hard-coding the margin-left and margin-top CSS properties of each modal I use, I would like the modals to resize and re-center themselves on the page when the size of the content changes (upon a user expanding a hidden section, for example). I'm using your open event to initially position the modal:

`$modalInstance.opened.then(function () {...});`

and I've attempted to place code that accomplishes the repositioning, upon content resize, inside a `resize` event (and used jQuery-UI's `resizeable()` method to make them resizeable):

`angular.element('#specific-modal').on('resize', function() {`
    `var dialog = angular.element('#specific-modal .modal-dialog');`
    `dialog.css('margin-top', ((angular.element($window).height() - dialog.height()) / 2) - parseInt(dialog.css('padding-top')));`
`});`
`angular.element('#specific-modal').resizable();`

However, the `resize` event is not firing. I've tried moving the `resize` event to every applicable node on the modal's DOM (`.modal-dialog`, `.modal-content`, etc.), without success. 

I'm wondering if there is anything extraordinary about the structure of your modals that would prevent such events from firing? I figured I'd ask, before I pull out the rest of my hair. Thanks, in advance.

**Comment by m-e-conroy** [comment]
I'm sorry i didn't get to your issue sooner, as I've been inundated with my real job of late.  Thanks for the compliment by the way.

As for you problem, i'm not sure if its up to this library to handle such an event.  I would think something like that should be handled by either Bootstrap itself or by Angular UI's modal object.  The DOM used follows those libraries, its possible that something within them is preventing the event capture.  I would think this is the case since Bootstrap supplies the ability to set the size of the modal (small, default and large).

Were you able to solve this?  I would be interested to know.
